### ISSUE TITLE
Unrecognized Operation TLV must elicit a response

### ISSUE THREAD

**Issue by pusateri** [raybellis/draft-bellis-dnsop-session-signal#30]
Section 4.2.2.4 says that an unrecognized Operation TLV must elicit a response. This conflicts if the A-bit is not set. Both cannot co-exist.

**Comment by pusateri** [comment]
If we add a DSO Fail TLV, it could be used to resolve this discrepancy. The operation TLV would still not elicit a response if the A-bit is not set but a DSO Fail TLV could indicate the failure to recognize the TLV.

**Comment by pusateri** [comment]
Stuart made the case that we should ignore unrecognized Operation TLVs that don't set the A bit. In other words, the A-Bit takes precedence.

**Comment by StuartCheshire** [comment]
I propose additional text along the following lines.

Get rid of ack bit in type codes:

* Spec for each individual TLV says if and when that TLV generates a response.

* Spec for primary TLV determines whether a particular request message generates a response message.

* Except for one case: An unrecognized primary TLV will return DSONOTIMP, even if the spec for that primary TLV says it generates no response (because the implementation doesn’t know about that spec). In reality this is not a problem because no-response primary TLVs are uncommon, and are only used in special cases where the sender already knows that the receiver understands this primary TLV (e.g., packets for mDNS relay proxy, Push Notifications). If a sender ever sends a no-response primary TLV to a receiver that doesn’t understand it and replies with a DSONOTIMP error, the sender is seriously broken.

Additional TLVs may be added to a request, but do not change whether that request message generates a response message. Only the primary TLV determines that.

**Comment by pusateri** [comment]
Fixed by Stuart in 759d44f056c59485f9257cdc1dca39090ffc8ded
