### ISSUE TITLE
Resolve QUIC transport 

### ISSUE THREAD

**Issue by pusateri** [raybellis/draft-bellis-dnsop-session-signal#7]
Need to finalize transport requirements and determine if QUIC meets those requirements

**Comment by saradickinson** [comment]
I now think the best thing to do is not to mention QUIC in this draft, and leave it so that if the QUIC draft wants to support this then the QUIC draft will have to find a mechanism to impose ordering where it is needed. (Since the fundamental conflict is that QUIC gets rid of head of line blocking by not having an ordered transport).

**Comment by StuartCheshire** [comment]
Agreed during 2nd August conference call: We will not mention QUIC explicitly in this document, but informally we will try not to require things that would make DNS Session Signaling gratuitously incompatible with QUIC.

**Comment by StuartCheshire** [comment]
Action: Need to delete paragraph that mentions QUIC in draft-ietf-dnsop-session-signal-03.

**Comment by raybellis** [comment]
resolved by https://github.com/raybellis/draft-bellis-dnsop-session-signal/commit/c51ec2828fbfa15cdbfb786d040c78245ba9f6dc

**Comment by StuartCheshire** [comment]
Agreed during 8th August conference call: We will make no mention of QUIC whatsoever, since we have no way to know how much QUIC may change between now and when QUIC becomes an RFC.
